const API_URL = import.meta.env.VITE_API_URL || "http://localhost:5000/api";

export interface User {
  id: number;
  email: string;
}

export interface Story {
  id: number;
  title: string;
  content: string;
  theme: string;
  characters: string[];
  ageGroup: string;
  isFavorite: boolean;
  imageUrl?: string;
  createdAt: string;
}

export interface LoginResponse {
  token: string;
  user: User;
}

export interface ErrorResponse {
  message: string;
}

export interface ShareData {
  shareUrl: string;
  shareData: {
    title: string;
    theme: string;
    characters: string[];
    ageGroup: string;
    imageUrl?: string;
    preview: string;
  };
}

async function fetchWithAuth(url: string, options: RequestInit = {}) {
  const headers = {
    "Content-Type": "application/json",
    ...options.headers,
  };

  try {
    const response = await fetch(`${API_URL}${url}`, {
      ...options,
      headers,
    });

    if (!response.ok) {
      const errorData = await response.json();
      throw new Error(errorData.message || "An error occurred");
    }

    return response.json();
  } catch (error) {
    console.error("API Error:", error);
    throw error;
  }
}

export async function login(email: string, password: string): Promise<LoginResponse> {
  return fetchWithAuth("/auth/login", {
    method: "POST",
    body: JSON.stringify({ email, password }),
  });
}

export async function register(email: string, password: string): Promise<void> {
  return fetchWithAuth("/auth/register", {
    method: "POST",
    body: JSON.stringify({ email, password }),
  });
}

export async function getCurrentUser(token: string): Promise<User> {
  if (!token) {
    throw new Error("Authentication token is required");
  }
  return fetchWithAuth("/auth/me", { method: "GET" });
}

export async function generateStory(
  theme: string,
  characters: string[],
  age_group: string,
  title?: string
): Promise<Story> {
  // Title is optional now, as it's auto-generated by the backend if not provided
  const payload = title ? { title, theme, characters, age_group } : { theme, characters, age_group };
  return fetchWithAuth("/stories", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export async function listStories(userId?: number): Promise<Story[]> {
  if (userId !== undefined) {
    return fetchWithAuth(`/stories?user_id=${userId}`, { method: "GET" });
  } else {
    return fetchWithAuth(`/stories`, { method: "GET" });
  }
}

export async function toggleFavorite(storyId: number): Promise<{ isFavorite: boolean }> {
  const result = await fetchWithAuth(`/stories/${storyId}/favorite`, { method: 'POST' });
  return { isFavorite: (result as any).isFavorite };
}

export async function regenerateIllustration(storyId: number): Promise<{ id: number, imageUrl: string }> {
  return fetchWithAuth(`/stories/${storyId}/regenerate-illustration`, { method: "POST" });
}

export async function deleteStory(storyId: number): Promise<void> {
  const response = await fetch(`${API_URL}/stories/${storyId}`, {
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json' },
  });
  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    throw new Error(errorData.message || 'Error deleting story');
  }
  return;
}

export async function getShareLink(storyId: number): Promise<ShareData> {
  return fetchWithAuth(`/stories/${storyId}/share`, {
    method: "GET",
  });
}